metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_PrintReceiptLabel.java
metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Transform.java

* transform-process: fixed field ordering a bit
FRESH-1609 metasfresh/metasfresh-webui#209 HU Automatic Label Printing
when received

Add process to manually print material receipt label if desired

---

metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_RunMaterialReceiptJasper.java

FRESH-1610 metasfresh/metasfresh-webui#210 Print Material Receipt
Document via Material Receipt Candidates Window

Add webui process WEBUI_M_ReceiptSchedule_RunMaterialReceiptJasper

---

metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Transform.java

FRESH-1504 metasfresh/metasfresh-webui#181 Transforming HU in Handling Unit Editor
FRESH-1692 metasfresh/metasfresh#1130 LU Transform "own Palette" Packing material

Transforming HU in Handling Unit Editor and LU "own Palette" packing material

---

src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocument.java
src/main/java/de/metas/ui/web/window/model/Document.java
src/main/java/de/metas/ui/web/window/model/DocumentChanges.java
src/main/java/de/metas/ui/web/window/model/DocumentChangesCollector.java
src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
src/main/java/de/metas/ui/web/window/model/HighVolumeReadonlyIncludedDocumentsCollection.java
src/main/java/de/metas/ui/web/window/model/IDocumentChangesCollector.java
src/main/java/de/metas/ui/web/window/model/IIncludedDocumentsCollection.java
src/main/java/de/metas/ui/web/window/model/IncludedDocumentsCollection.java
src/main/java/de/metas/ui/web/window/model/NullDocumentChangesCollector.java

task https://github.com/metasfresh/metasfresh-webui-api/issues/252

#252 Provide to frontend: tab allow create new and delete as they change

---

src/main/java/de/metas/ui/web/config/HostKeyConfig.java
src/main/java/de/metas/ui/web/login/LoginRestController.java

https://github.com/metasfresh/metasfresh-webui-api/issues/264

Gh264webui

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_CreateEmptiesReturns_Base.java
src/main/java/de/metas/ui/web/quickinput/inout/EmptiesQuickInputProcessor.java

task https://github.com/metasfresh/metasfresh/issues/1248

#1248 Empties movements are not generated from empties shipment/receipt

---

Jenkinsfile

https://github.com/metasfresh/metasfresh-webui-api/issues/283

Gh283 webui api

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_CreateEmptiesReturns_Base.java

https://metasfresh.atlassian.net/browse/FRESH-1589
https://github.com/metasfresh/metasfresh/issues/1064

#1064 Refactoring

---

Jenkinsfile
src/main/resources/application.properties

https://github.com/metasfresh/metasfresh-webui-frontend/issues/292
also providing the SHA1 to the webui-api's info

Gh292 webui frontend 2

---

pom.xml

Project "de.metas.material.dispo" shall not be part of Swing client https://github.com/metasfresh/metasfresh/issues/1515

Gh1515 metasfresh

---

pom.xml
src/main/resources/application.properties
src/main/resources/de/metas/ui/web/logging/STASH.xml
src/main/resources/de/metas/ui/web/logging/defaults.xml
src/main/resources/logback-spring.xml
src/main/resources/logback.xml

Configure our services for logstash https://github.com/metasfresh/metasfresh/issues/1504

Gh1504 metasfresh

---

src/main/java/de/metas/ui/web/address/AddressCountryLookupDescriptor.java
src/main/java/de/metas/ui/web/address/AddressRegionLookupDescriptor.java
src/main/java/de/metas/ui/web/pattribute/ASILookupDescriptor.java
src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
src/main/java/de/metas/ui/web/window/descriptor/ListLookupDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/LookupDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/SimpleLookupDescriptorTemplate.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlLookupDescriptor.java
src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
src/main/java/de/metas/ui/web/window/model/DocumentField.java
src/main/java/de/metas/ui/web/window/model/IDocumentFieldView.java
src/main/java/de/metas/ui/web/window/model/lookup/CachedLookupDataSourceFetcherAdapter.java
src/main/java/de/metas/ui/web/window/model/lookup/FullyCachedLookupDataSource.java
src/main/java/de/metas/ui/web/window/model/lookup/GenericSqlLookupDataSourceFetcher.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSource.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceAdapter.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceFetcher.java
src/main/java/de/metas/ui/web/window/model/lookup/NullLookupDataSource.java

https://github.com/metasfresh/metasfresh-webui-api/issues/381

ZoomInto shall consider AD_Ref_List.AD_Reference_ID if any

---

src/main/java/de/metas/ui/web/quickinput/WindowQuickInputRestController.java
src/main/java/de/metas/ui/web/window/controller/DocumentPermissionsHelper.java
src/main/java/de/metas/ui/web/window/datatypes/WindowId.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocument.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentPermissions.java

https://github.com/metasfresh/metasfresh-webui-api/issues/380

#380 apply readonly permissions

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorView.java

https://github.com/metasfresh/metasfresh-webui-api/issues/396

Gh396webui

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_ReturnFromCustomer.java

https://github.com/metasfresh/metasfresh/issues/1306

WEBUI_M_HU_ReturnFromCustomer

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuffer_HighVolume.java
src/main/java/de/metas/ui/web/view/SqlViewFactory.java
src/main/java/de/metas/ui/web/view/SqlViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/ViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewBinding.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewGroupingBinding.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewRowFieldBinding.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java
src/main/java/de/metas/ui/web/window/model/DocumentQueryOrderBy.java
src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentOrderByBuilder.java

https://github.com/metasfresh/metasfresh-webui-api/issues/424

Picking window WEBUI (WIP)

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Transform.java
src/main/java/de/metas/ui/web/handlingunits/util/WEBUI_ProcessHelper.java
src/main/java/de/metas/ui/web/picking/PickingCandidateCommand.java
src/main/java/de/metas/ui/web/picking/PickingHUsRepository.java
src/main/java/de/metas/ui/web/picking/PickingRow.java
src/main/java/de/metas/ui/web/picking/PickingSlotRow.java
src/main/java/de/metas/ui/web/picking/PickingSlotViewFactory.java
src/main/java/de/metas/ui/web/picking/PickingSlotViewRepository.java
src/main/java/de/metas/ui/web/picking/PickingView.java
src/main/java/de/metas/ui/web/picking/PickingViewFactory.java
src/main/java/de/metas/ui/web/picking/PickingViewRepository.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_M_Packageable_StartPicking.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_Picking_AddHUToPickingSlot.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_Picking_M_Picking_Candidate_Processed.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_Picking_PickSelectedHU.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_Picking_PickToExistingHU.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_Picking_PickToNewHU.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_Picking_RemoveHUFromPickingSlot.java
src/main/java/de/metas/ui/web/process/adprocess/WebuiProcessClassInfo.java
src/main/java/de/metas/ui/web/view/CreateViewRequest.java
src/test/java/de/metas/ui/web/picking/PickingHUsRepositoryTests.java
src/test/java/de/metas/ui/web/picking/PickingViewFactoryTests.java

https://github.com/metasfresh/metasfresh-webui-api/issues/503

Gh503 webui

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_InOut_Shipment_SelectHUs.java

https://github.com/metasfresh/metasfresh/issues/2142

#2142 Process for displaying the available HUs for a shipment

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToAnotherWarehouse.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToGarbage.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToQualityWarehouse.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_ReturnFromCustomer.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_ReturnToVendor.java

https://github.com/metasfresh/metasfresh/issues/2144

Gh2144 Move HUs to another warehouse

---

src/main/java/de/metas/ui/web/process/ProcessRestController.java
src/main/java/de/metas/ui/web/window/controller/Execution.java
src/main/java/de/metas/ui/web/window/model/Document.java
src/main/java/de/metas/ui/web/window/model/IDocumentChangesCollector.java
src/main/java/de/metas/ui/web/window/model/IDocumentField.java

https://github.com/metasfresh/metasfresh-webui-api/issues/551

verify if lookup value is still valid #551

---

src/main/java/de/metas/ui/web/attachments/DocumentAttachmentEntry.java

https://github.com/metasfresh/metasfresh-webui-api/issues/532

remove AttachmentEntry.getData()

---

src/main/java/de/metas/ui/web/document/filter/DocumentFilterDescriptorsProviderFactory.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java

https://github.com/metasfresh/metasfresh-webui-api/issues/564

default filter shall respect GridFieldVO.getSelectionColumnSeqNo()

---

src/main/java/de/metas/ui/web/pporder/PPOrderHUsToIssueActions.java

Minor adaption to method name change
https://github.com/metasfresh/metasfresh-webui-api/issues/590

Issues HUs are still selectable in HU editor while production is not completed #590

---

src/main/java/de/metas/ui/web/window/controller/DocumentPermissionsHelper.java

Handle incorrect AD_Window_ID in URL #603

Handle incorrect AD_Window_ID in URL #603

---

src/main/java/de/metas/ui/web/notification/UserNotificationDetailMessageFormat.java
src/main/java/de/metas/ui/web/window/model/Document.java

https://github.com/metasfresh/metasfresh/issues/2432

Process for converting any table to a document #2432

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorView.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuffer_FullyCached.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuffer_HighVolume.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactory.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableViewFactory.java
src/main/java/de/metas/ui/web/pickingslot/BrowsePickingSlotRow.java
src/main/java/de/metas/ui/web/pickingslot/BrowsePickingSlotsHUViewFactory.java
src/main/java/de/metas/ui/web/pickingslot/BrowsePickingSlotsHUViewIndexStorage.java
src/main/java/de/metas/ui/web/pickingslot/BrowsePickingSlotsView.java
src/main/java/de/metas/ui/web/pickingslot/BrowsePickingSlotsViewFactory.java
src/main/java/de/metas/ui/web/pickingslot/process/WEBUI_BrowsePickingSlots_Start.java
src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
src/main/java/de/metas/ui/web/view/CreateViewRequest.java
src/main/java/de/metas/ui/web/view/DefaultView.java
src/main/java/de/metas/ui/web/view/IViewDataRepository.java
src/main/java/de/metas/ui/web/view/IViewRow.java
src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
src/main/java/de/metas/ui/web/view/SqlViewFactory.java
src/main/java/de/metas/ui/web/view/SqlViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/ViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/ViewsRepository.java

https://github.com/metasfresh/metasfresh/issues/518

Browse picking slots and HUs view (WIP)

---

src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentsRepository.java

#639 Fix NPE

---

src/main/java/de/metas/ui/web/window/descriptor/factory/standard/DefaultValueExpressionsFactory.java

Material Dispo - map planning records with actual M_Transactions
https://github.com/metasfresh/metasfresh/issues/2684

Material Dispo - map planning records with actual M_Transactions #2684

---

src/main/java/de/metas/ui/web/board/BoardDescriptorRepository.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Pick_ParametersFiller.java
src/main/java/de/metas/ui/web/handlingunits/process/WebuiHUTransformParametersFiller.java
src/main/java/de/metas/ui/web/mail/WebuiMailRepository.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableViewRepository.java
src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotViewRepository.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessDescriptorsFactory.java
src/main/java/de/metas/ui/web/process/view/ViewActionParamDescriptor.java
src/main/java/de/metas/ui/web/quickinput/inout/EmptiesQuickInputDescriptorFactory.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlLookupDescriptor.java

https://github.com/metasfresh/metasfresh-webui-api/issues/633

Gh633 webui propagate tablename in column lookups

---

src/main/java/de/metas/ui/web/document/filter/sql/SqlDefaultDocumentFilterConverter.java

#2876 Fix Recreate printing queue for webui 
https://github.com/metasfresh/metasfresh/issues/2876

#2876 Fix Recreate printing queue for webui 

---

src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentsRepository.java

https://github.com/metasfresh/metasfresh/issues/2816

Material Dispo - include storage-relevant attributes #2816

---

pom.xml

#3042 C_Bpartner: new Additional fields
https://github.com/metasfresh/metasfresh/issues/3042

#3042 Add dependency

---

src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputDescriptorFactory.java
src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/forecastline/IForecastLineQuickInput.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

#699 Implement Batch entry in Forecast Window

#699 Implement Batch entry in Forecast Window 

---

src/main/java/de/metas/ui/web/dashboard/UserDashboardRepository.java

adapt to IQuery change Move UI Element Action broken
https://github.com/metasfresh/metasfresh/issues/3100

Move UI Element Action broken #3100

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRowAttributesHelper.java

https://github.com/metasfresh/metasfresh-webui-api/issues/727

Support Lookup view attributes

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToAnotherWarehouse.java

https://github.com/metasfresh/metasfresh/issues/2144

Gh2144 2 exclude warehouse of HU when moving to another warehouse

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToAnotherWarehouse.java

https://github.com/metasfresh/metasfresh/issues/2144

Gh2144 Branch renamed

---

src/main/java/de/metas/ui/web/address/AddressRepository.java
src/main/java/de/metas/ui/web/pattribute/ASIRepository.java
src/main/java/de/metas/ui/web/view/event/ViewChangesCollector.java
src/main/java/de/metas/ui/web/websocket/WebsocketSender.java
src/main/java/de/metas/ui/web/window/events/DocumentWebsocketPublisher.java

add the new API and change all the code to use it
refactor trx event listeners https://github.com/metasfresh/metasfresh/issues/3222

refactor trx event listeners #3222

---

src/main/java/de/metas/ui/web/document/process/WEBUI_Fact_Acct_Repost.java
src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
src/main/java/de/metas/ui/web/view/DefaultView.java
src/main/java/de/metas/ui/web/view/IView.java
src/main/java/de/metas/ui/web/view/IViewDataRepository.java
src/main/java/de/metas/ui/web/view/IViewRow.java
src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
src/main/java/de/metas/ui/web/view/SqlViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/ViewRowIdsOrderedSelectionFactory.java

https://github.com/metasfresh/metasfresh/issues/3213

Gh3213 repost in webui

---

src/main/java/de/metas/ui/web/session/FixedMapSessionRepository.java
src/main/java/de/metas/ui/web/session/SessionConfig.java
src/main/java/de/metas/ui/web/view/DefaultView.java
src/main/java/de/metas/ui/web/view/IViewDataRepository.java
src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
src/main/java/de/metas/ui/web/view/SqlViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/SqlViewSelectionToDeleteHelper.java
src/main/java/de/metas/ui/web/view/ViewConfiguration.java
src/main/java/de/metas/ui/web/view/ViewRowIdsOrderedSelectionFactory.java

https://github.com/metasfresh/metasfresh-webui-api/issues/737

DefaultView.close shall schedule selectionIds to be deleted

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUIHUCreationWithSerialNumberService.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_Add_Batch_SerialNo_To_CUs.java
src/main/java/de/metas/ui/web/handlingunits/process/WebuiHUTransformCommand.java
src/main/java/de/metas/ui/web/handlingunits/process/WebuiHUTransformParameters.java

https://github.com/metasfresh/metasfresh/issues/3209

Gh3209 Working increments

---

src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitRowRepository.java
src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitView.java
src/main/java/de/metas/ui/web/picking/PickingTerminalViewInvalidationAdvisor.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableRow.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableRowsData.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableView.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableViewRepository.java
src/main/java/de/metas/ui/web/view/AbstractCustomView.java
src/main/java/de/metas/ui/web/view/DefaultView.java
src/main/java/de/metas/ui/web/view/DefaultViewInvalidationAdvisor.java
src/main/java/de/metas/ui/web/view/IView.java
src/main/java/de/metas/ui/web/view/IViewInvalidationAdvisor.java
src/main/java/de/metas/ui/web/view/SqlViewFactory.java
src/main/java/de/metas/ui/web/view/SqlViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewBinding.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java
src/main/java/de/metas/ui/web/view/event/ViewChanges.java
src/main/java/de/metas/ui/web/view/event/ViewChangesCollector.java
src/test/java/de/metas/ui/web/material/cockpit/MaterialCockpitRowRepositoryTest.java

https://github.com/metasfresh/metasfresh-webui-api/issues/810

Update QtyPicked after picking

---

src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRow.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/SalesOrder2PurchaseViewFactory.java
src/main/java/de/metas/ui/web/view/IViewRow.java
src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumnHelper.java
src/main/java/de/metas/ui/web/window/datatypes/Values.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentField.java

#818 Values.valueToJsonObject() shall return JSONNullValue instead of null

---

src/main/java/de/metas/ui/web/pickingslotsClearing/process/WEBUI_PackingHUsView_AddHUsToShipperTransportationShipAndInvoice.java

https://github.com/metasfresh/metasfresh-webui-api/issues/806

#806-api Add to Transportation Order, Ship and Invoice action in Picking Clearing Tray shall respect the invoice schedule

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUIHUCreationWithSerialNumberService.java

https://github.com/metasfresh/metasfresh/issues/3209

Gh3209 2 Repaired a case that had an error

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuffer_FullyCached.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_InOut_Shipment_SelectHUs.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveCUs.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveHUs_Base.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_SelectHUsToReverse.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRow.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactory.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoader.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsSaver.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/SalesOrder2PurchaseViewFactory.java
src/main/java/de/metas/ui/web/picking/process/WEBUI_Picking_Launcher.java
src/main/java/de/metas/ui/web/view/ViewRestController.java
src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumnHelper.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

https://github.com/metasfresh/metasfresh/issues/3437

#3437 MSV3 handle deviating response from remote MSV3 server

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUIHUCreationWithSerialNumberService.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_Add_Batch_SerialNo_To_CUs.java

https://github.com/metasfresh/metasfresh/issues/3452

Gh3452 Repair the TU:CU case

---

src/main/java/de/metas/ui/web/document/filter/DocumentFilter.java
src/main/java/de/metas/ui/web/document/filter/DocumentFilterParam.java
src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitRowRepository.java
src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitView.java
src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitViewFactory.java
src/main/java/de/metas/ui/web/material/cockpit/filters/MaterialCockpitFilters.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableView.java
src/main/java/de/metas/ui/web/view/AbstractCustomView.java
src/main/java/de/metas/ui/web/view/DefaultView.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlLookupDescriptor.java

https://github.com/metasfresh/metasfresh-webui-api/issues/857

Material Cockpit additional Filter criteria

---

src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocument.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentField.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentFieldWarning.java
src/main/java/de/metas/ui/web/window/model/DocumentChanges.java
src/main/java/de/metas/ui/web/window/model/DocumentChangesCollector.java
src/main/java/de/metas/ui/web/window/model/DocumentFieldAsCalloutField.java
src/main/java/de/metas/ui/web/window/model/DocumentFieldChange.java
src/main/java/de/metas/ui/web/window/model/DocumentFieldWarning.java
src/main/java/de/metas/ui/web/window/model/IDocumentChangesCollector.java
src/main/java/de/metas/ui/web/window/model/NullDocumentChangesCollector.java

=> introduced DocumentFieldWarning
https://github.com/metasfresh/metasfresh/issues/3516

implement DocumentFieldAsCalloutField.fireDataStatusEEvent

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
src/main/java/de/metas/ui/web/handlingunits/util/TUPackingInfo.java
src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/3503

#3503 Use correct picking quantities in shipment

---

src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToExistingHU.java
src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToNewHU.java

https://github.com/metasfresh/metasfresh-webui-api/issues/820

Gh820 webui picking details

---

src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToExistingHU.java
src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToNewHU.java

https://github.com/metasfresh/metasfresh-webui-api/issues/820

Gh820 webui other details solved

---

Jenkinsfile

Use nexus.metasfresh.com as docker repo metasfresh/metasfresh-jenkins-pipeline#4

Gh4 jenkins

---

src/main/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapter.java
src/main/java/de/metas/ui/web/material/adapter/AvailableToPromiseResultForWebui.java
src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputDescriptorFactory.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
src/test/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapterTests.java
src/test/java/de/metas/ui/web/material/adapter/README.md

https://github.com/metasfresh/metasfresh/issues/3541

#3541 Div material dispo issues

---

Jenkinsfile

https://github.com/metasfresh/metasfresh-jenkins-pipeline/issues/5

#5-jenkins Refactor docker related code

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Pick.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Pick_ParametersFiller.java
src/main/java/de/metas/ui/web/handlingunits/util/WEBUI_ProcessHelper.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlLookupDescriptor.java

add validation logic to WEBUI_M_HU_Pick_ParametersFiller
* for shipment schedules, also filter by HU's C_BPartner, if any
* for picking slots, filter for available slots (depending on selected shipment schedule)
* also minor code changes (unrelated)
Pick in manufacturing Order: Picking Slot Filter on selected BPartner from Shipment Schedule metasfresh/metasfresh#3634

#3634-app - Pick in manufacturing Order: Picking Slot Filter on selected BPartner from Shipment Schedule

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuffer_FullyCached.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewRepository.java
src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
src/main/java/de/metas/ui/web/picking/PickingTerminalViewInvalidationAdvisor.java
src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
src/main/java/de/metas/ui/web/view/SqlViewFactory.java
src/main/java/de/metas/ui/web/view/SqlViewRowIdsOrderedSelectionFactory.java
src/main/java/de/metas/ui/web/view/ViewEvaluationCtx.java
src/main/java/de/metas/ui/web/view/ViewRow.java
src/main/java/de/metas/ui/web/view/descriptor/SqlAndParams.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewBinding.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewKeyColumnNamesMap.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectData.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java
src/main/java/de/metas/ui/web/window/datatypes/DocumentId.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GenericDocumentSummaryValueProvider.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/PlainSqlEntityFieldBinding.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlDocumentEntityDataBindingDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlDocumentFieldDataBindingDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlEntityBinding.java
src/main/java/de/metas/ui/web/window/model/Document.java
src/main/java/de/metas/ui/web/window/model/DocumentReferencesService.java
src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentQueryBuilder.java
src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentsRepository.java
src/test/java/de/metas/ui/web/picking/pickingslot/MockedHUEditorViewRepository.java
src/test/java/de/metas/ui/web/view/descriptor/SqlViewBindingTest.java

https://github.com/metasfresh/metasfresh-webui-api/issues/894

New Composed Primary Keys

---

src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToNewHU.java

https://github.com/metasfresh/metasfresh-webui-api/issues/895

Gh895 webui Auto Print Picking Label

---

src/main/java/de/metas/ui/web/pickingslotsClearing/process/PickingSlotsClearingViewBasedProcess.java
src/main/java/de/metas/ui/web/pickingslotsClearing/process/WEBUI_PickingSlotsClearingView_TakeOutHUAndAddToNewHU.java

Toplevel TUs are created as aggregate HUs https://github.com/metasfresh/metasfresh/issues/3739

#3739-app - Toplevel TUs are created as aggregate HUs

---

src/main/java/de/metas/ui/web/window/model/DocumentReferencesService.java

ZoomTo - exception in console if IsGenericZoomOrigin='N' https://github.com/metasfresh/metasfresh/issues/3746

#3746-app - ZoomTo - exception in console if IsGenericZoomOrigin='N' 

---

src/main/java/de/metas/ui/web/product/process/WEBUI_Block_Product_Locked_LotNo.java
src/main/java/de/metas/ui/web/product/process/WEBUI_M_Product_LotNumber_Lock.java

https://github.com/metasfresh/metasfresh/issues/3721

Gh3721 Request after Quarantine DD Order

---

src/main/java/de/metas/ui/web/product/process/WEBUI_Block_Product_Locked_LotNo.java
src/main/java/de/metas/ui/web/product/process/WEBUI_M_Product_LotNumber_Lock.java

https://github.com/metasfresh/metasfresh/issues/3693

Gh3693 Block locked lotNo

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveHUs_Base.java

Regression on process M_ReceiptSchedule_Generate_M_InOuts https://github.com/metasfresh/metasfresh/issues/3773

#3773-app - Regression on process M_ReceiptSchedule_Generate_M_InOuts 

---

src/main/java/de/metas/ui/web/product/process/WEBUI_M_Product_LotNumber_Lock.java

https://github.com/metasfresh/metasfresh/issues/3693

Gh3693 plus Make DD_Order and Request with partner from Receipt

---

src/main/java/de/metas/ui/web/ddorder/process/WEBUI_DD_OrderLine_MoveHU.java

https://github.com/metasfresh/metasfresh/issues/3776

Gh3776 Show Default HU in Distribution Editor

---

src/main/java/de/metas/ui/web/picking/husToPick/process/WEBUI_HUsToPick_PickCU.java

https://github.com/metasfresh/metasfresh/issues/3778

#3778  Automatically process Picking CU if config is like so

---

src/main/java/de/metas/ui/web/picking/husToPick/process/WEBUI_HUsToPick_PickCU.java

https://github.com/metasfresh/metasfresh/issues/3778

#3778 I think the HU before was wrong. Also refactoring

---

src/main/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapter.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRow.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactoryTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

https://github.com/metasfresh/metasfresh/issues/3777

#3777-app - Show available to promise in Procurement Dispo modal in Sales Order

---

src/main/java/de/metas/ui/web/quickinput/invoiceline/InvoiceLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/3834

#3834-app - Do not allow banned products in order and invoice 

---

src/main/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapter.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRow.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactory.java

https://github.com/metasfresh/metasfresh/issues/3777

Gh3777 display atp according to line's asi

---

src/main/java/de/metas/ui/web/pharma/process/WEBUI_C_BPartner_UpdateCustomerPharmaPermissions.java
src/main/java/de/metas/ui/web/pharma/process/WEBUI_C_BPartner_UpdateVendorPharmaPermissions.java
src/main/java/de/metas/ui/web/pharma/process/WEBUI_UpdateCustomerPharmaPermissions.java

https://github.com/metasfresh/metasfresh/issues/3890

Gh3890 update pharma permissions

---

src/main/java/de/metas/ui/web/handlingunits/report/HUReportProcessInstancesRepository.java

follow changes in metasfresh
https://github.com/metasfresh/metasfresh/issues/3895 extend M_HU_Process

#3895-app - extend M_HU_Process

---

src/main/java/de/metas/ui/web/window/model/Document.java

https://github.com/metasfresh/metasfresh/issues/3891

gh3891-webui: Propagate user validation errors directly to user

---

src/main/java/de/metas/ui/web/picking/PickingTerminalByOrderViewCustomizer.java
src/main/java/de/metas/ui/web/picking/PickingTerminalByWarehouseAndProductViewCustomizer.java
src/main/java/de/metas/ui/web/picking/husToPick/process/WEBUI_HUsToPick_PickCU.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableRow.java
src/main/java/de/metas/ui/web/picking/packageable/PackageableViewRepository.java

https://github.com/metasfresh/metasfresh/issues/3923

#3923 make sure the qtys are updated after pick CU with auto process

---

src/main/java/de/metas/ui/web/address/AddressCountryLookupDescriptor.java
src/main/java/de/metas/ui/web/address/AddressPostalLookupDescriptor.java
src/main/java/de/metas/ui/web/address/AddressRegionLookupDescriptor.java
src/main/java/de/metas/ui/web/pattribute/ASILookupDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/LookupDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/SimpleLookupDescriptorTemplate.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlLookupDescriptor.java
src/main/java/de/metas/ui/web/window/model/lookup/CachedLookupDataSourceFetcherAdapter.java
src/main/java/de/metas/ui/web/window/model/lookup/FullyCachedLookupDataSource.java
src/main/java/de/metas/ui/web/window/model/lookup/GenericSqlLookupDataSourceFetcher.java
src/main/java/de/metas/ui/web/window/model/lookup/LabelsLookup.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupCacheInvalidationDispatcher.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSource.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceAdapter.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceFactory.java
src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceFetcher.java
src/main/java/de/metas/ui/web/window/model/lookup/NullLookupDataSource.java

https://github.com/metasfresh/metasfresh-webui-api/issues/954

#954-api - Allow configuring lookup cache reset on table record changes

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUIHUCreationWithSerialNumberService.java
src/main/java/de/metas/ui/web/notification/UserNotificationDetailMessageFormat.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlLookupDescriptor.java

https://github.com/metasfresh/metasfresh/issues/3926

#3926-app - Implement support for `der Kurier` shipper

---

src/main/java/de/metas/ui/web/product/process/WEBUI_M_Product_LotNumber_Lock.java

https://github.com/metasfresh/metasfresh/issues/4013

#4013 Do not throw exception if the banning process runs for existing lot numbers

---

src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRow.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactory.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/SalesOrder2PurchaseViewFactory.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactoryTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

#4001-app - Calculate Purchase price with yearly Bonus

---

src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

metasfresh/metasfresh#4088
metasfresh/metasfresh#4036

#4088-app - Add profit/margin infos to purchase candidates

---

src/main/java/de/metas/ui/web/handlingunits/process/WebuiHUTransformParametersFiller.java

https://github.com/metasfresh/metasfresh/issues/4122

#4122 bug repaired

---

src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_HUEditor_Launcher.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_ReverseCandidate.java

https://github.com/metasfresh/metasfresh/issues/3463

#3463 display actions for removing HU for IssueOnlyWhatWasReceived lines

---

src/main/java/de/metas/ui/web/letter/LetterRestController.java

#4153 Serial Letter Feature
https://github.com/metasfresh/metasfresh/issues/4153

#4153 Use Letter model

---

src/main/java/de/metas/ui/web/letter/LetterRestController.java

#4153 Serial Letter Feature
https://github.com/metasfresh/metasfresh/issues/4153

#4153 Fix compiling issue

---

src/main/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapter.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseCandidates2PurchaseViewFactory.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRow.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactory.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowId.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoader.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsSaver.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseViewFactoryTemplate.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/SalesOrder2PurchaseViewFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactoryTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowIdTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

Pharma: MSV3 Purchase Functionality in purchase candidates https://github.com/metasfresh/metasfresh/issues/4033

#4033-app - Pharma: MSV3 Purchase Functionality in purchase candidates

---

src/main/java/de/metas/ui/web/quickinput/invoiceline/InvoiceLineQuickInputProcessor.java

#4223 Ban Manufacturer Products for a Businesspartner
https://github.com/metasfresh/metasfresh/issues/4223

#4223 Use BPartnerId and ProductId

---

src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/4218

Gh4218 Do not allow prescription drugs in sales order if permission lacks

---

src/main/java/de/metas/ui/web/product/process/WEBUI_M_Product_LotNumber_Lock.java

https://github.com/metasfresh/metasfresh/issues/4220

#4220 Support banning lotNo without product

---

src/main/java/de/metas/ui/web/order/sales/hu/reservation/HUReservationDocumentFilterService.java
src/main/java/de/metas/ui/web/picking/husToPick/HUsToPickViewFactory.java

https://github.com/metasfresh/metasfresh/issues/4276

#4276 improve filtering in picking terminal

---

src/main/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapter.java

ATP Stock indicator in Sales Orderline https://github.com/metasfresh/metasfresh/issues/4212

#4212 follow a class rename in metasfresh

---

src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/4218

#4218 refactoring

---

src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

https://github.com/metasfresh/metasfresh/issues/4311

adapt unit test

---

src/main/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapter.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
src/test/java/de/metas/ui/web/material/adapter/AvailableToPromiseAdapterTests.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactoryTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

Follow the refactoring in metasfresh
https://github.com/metasfresh/metasfresh/issues/4342

#4342-app - ATP in batch entry is wrong after attributes are added 

---

src/main/java/de/metas/ui/web/window/descriptor/sql/AutoSequenceDefaultValueExpression.java

* follow refactoring in metasfresh
https://github.com/metasfresh/metasfresh/issues/4346

#4346 - Individual sequences for products and projects

---

src/main/java/de/metas/purchasecandidate/interceptor/C_PurchaseCandidate.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/BasePricingSystemPriceCalculator.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/OrderLinePricingConditionsViewFactory.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/PricingConditionsRow.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/PricingConditionsRowActions.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/PricingConditionsRowChangeRequest.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/PricingConditionsRowLookups.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/PricingConditionsRowReducers.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/PricingConditionsRowsLoader.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/PricingConditionsView.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/ProductPricingConditionsViewFactory.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRow.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactory.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsCollection.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoader.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsSaver.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseView.java
src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/SalesOrder2PurchaseViewFactory.java
src/main/java/de/metas/ui/web/purchasecandidate/interceptor/C_PurchaseCandidate.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/DoNothingPurchaseProfitInfoServiceImpl.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactoryTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowTestTools.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

https://github.com/metasfresh/metasfresh/issues/4380

#4380-app - consolidate profit related columns in order line and purchase candidate

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Transform.java
src/main/java/de/metas/ui/web/handlingunits/process/WebuiHUTransformParametersFiller.java

https://github.com/metasfresh/metasfresh/issues/4367

Gh4367 Parameter callout for HU Transform -> TU to new LU

---

src/main/java/de/metas/ui/web/board/BoardDescriptorRepository.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorView.java
src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_CreateReceipt_LocatorParams.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_ReturnTUsToVendor.java
src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitRow.java
src/main/java/de/metas/ui/web/material/cockpit/mapping_new_to_legacy.md
src/main/java/de/metas/ui/web/material/cockpit/rowfactory/CountingSubRowBucket.java
src/main/java/de/metas/ui/web/material/cockpit/rowfactory/DimensionGroupSubRowBucket.java
src/main/java/de/metas/ui/web/material/cockpit/rowfactory/MainRowBucket.java
src/main/java/de/metas/ui/web/material/cockpit/rowfactory/MainRowWithSubRows.java
src/main/java/de/metas/ui/web/order/sales/hu/reservation/HUReservationDocumentFilterService.java
src/main/java/de/metas/ui/web/order/sales/hu/reservation/process/WEBUI_C_OrderLineSO_Launch_HUEditor.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/process/WEBUI_SalesOrder_PricingConditionsView_Launcher.java
src/main/java/de/metas/ui/web/order/sales/pricingConditions/view/OrderLinePricingConditionsViewFactory.java
src/main/java/de/metas/ui/web/picking/husToPick/HUsToPickViewFactory.java
src/main/java/de/metas/ui/web/picking/husToPick/process/WEBUI_HUsToPick_PickCU.java
src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_HUEditor_Launcher.java
src/main/java/de/metas/ui/web/view/CreateViewRequest.java
src/main/java/de/metas/ui/web/view/ViewRow.java
src/main/java/de/metas/ui/web/view/descriptor/ViewLayout.java
src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumn.java
src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumnHelper.java
src/main/java/de/metas/ui/web/view/json/JSONCreateViewRequest.java
src/main/java/de/metas/ui/web/view/json/JSONViewDataType.java
src/main/java/de/metas/ui/web/window/datatypes/LookupValues.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementDescriptor.java
src/test/java/de/metas/ui/web/material/cockpit/rowfactory/MaterialCockpitRowFactoryTest.java

https://github.com/metasfresh/metasfresh/issues/4454

#4454-app - Material Cockpit - add columns and allow to hide columns via config

---

src/main/java/de/metas/ui/web/material/cockpit/rowfactory/MaterialCockpitRowFactory.java

https://github.com/metasfresh/metasfresh/issues/4456

#4456-app Material Cockpit - attribute detail rows' dimenstion spec

---

src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseViewFactoryTemplate.java

* remove the interface mostly change IProcess to JavaProcess
Get rid of the legacy IProcess interface https://github.com/metasfresh/metasfresh/issues/4467

#4467-app - Get rid of the legacy IProcess interface

---

src/main/java/de/metas/ui/web/view/descriptor/SqlViewKeyColumnNamesMap.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlDocumentEntityDataBindingDescriptor.java

The fix is in GridTabVOBasedDocumentEntityDescriptorFactory (afaiu I introduced the bug yesterday :-$ )
Error opening translation windows https://github.com/metasfresh/metasfresh-webui-api/issues/1025

#1025-api - Error opening translation windows

---

src/main/java/de/metas/ui/web/picking/husToPick/HUsToPickViewFilters.java

#4526 Filter for attributes in picking terminal shall be set by default
https://github.com/metasfresh/metasfresh/issues/4526

#4526 set default on true

---

src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayoutElement.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayoutElementField.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementFieldDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java

#1037-api - Advanced tooltip support

---

src/main/java/de/metas/ui/web/attachments/DocumentArchiveEntry.java
src/main/java/de/metas/ui/web/attachments/DocumentAttachmentEntry.java
src/main/java/de/metas/ui/web/attachments/DocumentAttachments.java
src/main/java/de/metas/ui/web/attachments/DocumentAttachmentsRestController.java
src/main/java/de/metas/ui/web/attachments/IDocumentAttachmentEntry.java

https://github.com/metasfresh/metasfresh/issues/4636

#4636-app Support attachments being linked to multiple records

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
src/main/java/de/metas/ui/web/order/sales/hu/reservation/HUsReservationViewFactory.java
src/main/java/de/metas/ui/web/picking/husToPick/HUsToPickViewFactory.java
src/main/java/de/metas/ui/web/receiptSchedule/HUsToReceiveViewFactory.java
src/main/java/de/metas/ui/web/view/descriptor/ViewLayout.java
src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumn.java
src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumnHelper.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/WidgetSize.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java

https://github.com/metasfresh/metasfresh/issues/4609

Gh4609  HUEditor-Tweaks

---

src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java
src/main/java/de/metas/ui/web/order/sales/hu/reservation/HUsReservationViewFactory.java
src/main/java/de/metas/ui/web/picking/husToPick/HUsToPickViewFactory.java
src/main/java/de/metas/ui/web/view/descriptor/annotation/ViewColumnHelper.java

https://github.com/metasfresh/metasfresh/issues/4609

#4609 hu Tweaks improvements

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_CreateReceipt_Base.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_CreateReceipt_LocatorParams.java

https://github.com/metasfresh/metasfresh/issues/4567

Gh4567 improve process receipt create with locator

---

src/main/java/de/metas/ui/web/view/ViewExcelExporter.java

https://github.com/metasfresh/metasfresh/issues/4633

webui: gh4633

---

src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitRow.java
src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitViewFactory.java

https://github.com/metasfresh/metasfresh/issues/4640

#4640 option to not see the included rows in material cockpit

---

src/main/java/de/metas/ui/web/attachments/DocumentAttachmentEntry.java

* follow refactoring in metasfresh
https://github.com/metasfresh/metasfresh/issues/4700

#4700-app - Allow appending additional PDF-attachments to invoice-PDF

---

src/main/java/de/metas/ui/web/handlingunits/trace/HuTraceQueryCreator.java
src/test/java/de/metas/ui/web/handlingunits/DocumentFilterToHuTraceQueryTest.java

https://github.com/metasfresh/metasfresh/issues/4705

adapt after fixes in metasfresh

---

src/main/java/de/metas/ui/web/pporder/PPOrderLinesLoader.java
src/main/java/de/metas/ui/web/pporder/PPOrderLinesView.java
src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewData.java
src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewDataSupplier.java
src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_ChangePlanningStatus_Complete.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_ChangePlanningStatus_Planning.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_ChangePlanningStatus_Review.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_ChangePlanningStatus_Template.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_HUEditor_IssueTUs.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_HUEditor_IssueTopLevelHUs.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueCUQty.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueTuQty.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Receipt.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1097

metasfresh-webui: "Issue only for what was received" method: Issued HUs remain issued and don't get destroyed 

---

src/main/java/de/metas/ui/web/document/filter/MQueryDocumentFilterHelper.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentReference.java
src/main/java/de/metas/ui/web/window/model/DocumentReference.java
src/main/java/de/metas/ui/web/window/model/DocumentReferencesService.java

* forward the ZoomInfo's InternalName to the APIs JSON response
https://github.com/metasfresh/metasfresh-webui-api/issues/1111

#1111-api - Include internalName in JSONReference

---

src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_4EyesReview_ProcessAll.java
src/main/java/de/metas/ui/web/pickingslotsClearing/process/WEBUI_PackingHUsView_AddHUsToShipperTransportationShipAndInvoice.java
src/main/java/de/metas/ui/web/quickinput/WindowQuickInputRestController.java

invoice and async improvements https://github.com/metasfresh/metasfresh/issues/4825

 invoice and async improvements

---

src/main/java/de/metas/ui/web/window/model/lookup/LookupDataSourceContext.java

fix after having improved TimeUtil.asDate() in metasfresh
https://github.com/metasfresh/metasfresh/issues/4805

4805-app - ATP not correct after partial material receipt

---

src/main/java/de/metas/ui/web/order/pricingconditions/process/PricingConditionsView_CopyRowToEditable.java
src/main/java/de/metas/ui/web/order/pricingconditions/process/PricingConditionsView_SaveEditableRow.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/OrderLinePricingConditionsViewFactory.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsRow.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsRowActions.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsRowChangeRequest.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsRowLookups.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsRowReducers.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsRowsLoader.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsView.java
src/main/java/de/metas/ui/web/websocket/WebSocketConfig.java

https://github.com/metasfresh/metasfresh/issues/4282

4282-app - Order line is flagged as Temporary Pricing Conditions when the conditions are actually missing

---

src/main/java/de/metas/ui/web/process/adprocess/ADProcessDescriptorsFactory.java
src/main/java/de/metas/ui/web/process/descriptor/ProcessDescriptor.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1123

1123-api - Fix process parameter translations

---

src/main/java/de/metas/ui/web/document/filter/sql/SqlParamsCollector.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java

https://github.com/metasfresh/metasfresh/issues/4906

ProductLookupDescriptor: consider base PLVs too

---

src/main/java/de/metas/ui/web/debug/DebugRestController.java
src/main/java/de/metas/ui/web/order/products_proposal/view/BPartnerProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java

use BPartnerId
https://github.com/metasfresh/metasfresh/issues/4894

4894-app - BPartner Product statistics: LastShipmentDate, LastReceiptDate

---

src/main/java/de/metas/ui/web/order/products_proposal/process/ProductsProposalViewBasedProcess.java
src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_AddProductFromBasePriceList.java
src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_CancelAddingProductFromBasePriceList.java
src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_SaveProductPriceToCurrentPriceListVersion.java
src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_ShowProductsToAddFromBasePriceList.java
src/main/java/de/metas/ui/web/order/products_proposal/view/BPartnerProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/BasePLVProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderLinesFromProductProposalsProducer.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowActions.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowChangeRequest.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowReducers.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowsData.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalView.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalViewFactoryTemplate.java
src/main/java/de/metas/ui/web/view/IView.java
src/main/java/de/metas/ui/web/view/descriptor/ViewLayout.java
src/main/java/de/metas/ui/web/window/datatypes/DocumentIdIntSequence.java
src/main/java/de/metas/ui/web/window/descriptor/ViewEditorRenderMode.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1132

Gh1132webui 3

---

src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueCUQty.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueTuQty.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Template.java

https://github.com/metasfresh/metasfresh-webui-api/pull/1143 Make Issue CUs/TUs from Source HU work for Multi Select

#1142 Make Issue CUs/TUs from Source HU work for Multi Select 

---

src/main/java/de/metas/ui/web/document/filter/DocumentFilter.java
src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsViewFactoryTemplate.java
src/main/java/de/metas/ui/web/order/products_proposal/view/BasePLVProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowsData.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalView.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalViewFilter.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalViewFilters.java
src/main/java/de/metas/ui/web/pporder/PPOrderLinesViewFactory.java
src/main/java/de/metas/ui/web/view/IViewFactory.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1132

Gh1132webui 4

---

src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueCUQty.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueTuQty.java
src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Template.java

#1142 Make Issue CUs/TUs from Source HU work for Multi Select

#1142 Make Issue CUs from Source HU work for Multi Select 

---

src/main/java/de/metas/ui/web/quickinput/IQuickInputDescriptorFactory.java
src/main/java/de/metas/ui/web/quickinput/QuickInputDescriptorFactoryService.java
src/main/java/de/metas/ui/web/quickinput/WindowQuickInputRestController.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java

https://github.com/metasfresh/metasfresh/pull/4960

Gh1146webui

---

src/main/java/de/metas/ui/web/handlingunits/report/HUReportProcessInstance.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsData.java
src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_Delete.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalView.java
src/main/java/de/metas/ui/web/process/IProcessInstanceController.java
src/main/java/de/metas/ui/web/process/ProcessId.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessDescriptorsFactory.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessInstanceController.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessInstancesRepository.java
src/main/java/de/metas/ui/web/process/descriptor/ProcessDescriptor.java
src/main/java/de/metas/ui/web/process/descriptor/ProcessLayout.java
src/main/java/de/metas/ui/web/process/json/JSONProcessInstance.java
src/main/java/de/metas/ui/web/process/view/ViewActionInstance.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1150

WEBUI_ProductsProposal_Delete process

---

src/main/java/de/metas/ui/web/order/products_proposal/campaign_price/CampaignPriceProvider.java
src/main/java/de/metas/ui/web/order/products_proposal/campaign_price/CampaignPriceProviders.java
src/main/java/de/metas/ui/web/order/products_proposal/campaign_price/NullCampaignPriceProvider.java
src/main/java/de/metas/ui/web/order/products_proposal/campaign_price/StandardCampaignPriceProvider.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductProposalCampaignPrice.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductProposalPrice.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowReducers.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsData.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_AddProductFromBasePriceList.java
src/main/java/de/metas/ui/web/order/products_proposal/process/WEBUI_ProductsProposal_SaveProductPriceToCurrentPriceListVersion.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLinesFromProductProposalsProducer.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OtherSalePricesProductsProposalViewFactory.java

OrderLinesFromProductProposalsProducer

Gh1152webui

---

Jenkinsfile

https://github.com/metasfresh/metasfresh-e2e/issues/4

4-e2e - Reorganize and further integrate e2e into CI process

---

Jenkinsfile
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/ADTabLoader.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java

fix underlying NPE problem by returning Optional.empty instead of null
https://github.com/metasfresh/metasfresh-webui-api/issues/1163

1163-webapi - Warehouse cannot be created / opening window causes error

---

src/main/java/de/metas/ui/web/document/filter/DocumentFilterDescriptorsProviderFactory.java
src/main/java/de/metas/ui/web/document/filter/UserQueryDocumentFilterDescriptorsProvider.java
src/main/java/de/metas/ui/web/view/DefaultView.java
src/main/java/de/metas/ui/web/view/IViewDataRepository.java
src/main/java/de/metas/ui/web/view/SqlViewDataRepository.java
src/main/java/de/metas/ui/web/view/SqlViewFactory.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewBinding.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewKeyColumnNamesMap.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentEntityDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/model/DocumentAsCalloutRecord.java
src/test/resources/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoaderTest.snap

https://github.com/metasfresh/metasfresh-webui-api/issues/1178

Gh1178webui

---

src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

Implements: https://github.com/metasfresh/metasfresh/issues/5071
Related to https://github.com/metasfresh/metasfresh/pull/5088

Gh5071 part 2: Don't allow narcotics in Trade Sales

---

src/main/java/de/metas/ui/web/pharma/process/WEBUI_C_BPartner_UpdateCustomerPharmaPermissions.java
src/main/java/de/metas/ui/web/pharma/process/WEBUI_C_BPartner_UpdateVendorPharmaPermissions.java

https://github.com/metasfresh/metasfresh/issues/5095

Enable set/unset of BPartner narcotics pharma permission

---

Jenkinsfile
src/main/java/de/metas/ui/web/window/model/sql/SqlValueConverters.java

* follow refactoring in metasfresh
* minor change in Jenkinsfile
https://github.com/metasfresh/metasfresh/issues/5108

Short term availability check for sales orders

---

src/main/java/de/metas/ui/web/address/AddressPostalLookupDescriptor.java
src/main/java/de/metas/ui/web/order/products_proposal/campaign_price/StandardCampaignPriceProvider.java
src/main/java/de/metas/ui/web/order/products_proposal/view/BPartnerProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java

Part 1 of https://github.com/metasfresh/metasfresh/issues/5101
Related to https://github.com/metasfresh/metasfresh/pull/5132

Add Geocoding capabilities

---

src/main/java/de/metas/ui/web/window/descriptor/factory/standard/DefaultValueExpressionsFactory.java
src/main/java/de/metas/ui/web/window/model/DocumentsRepository.java

fix the problem without causing new trouble
https://github.com/metasfresh/metasfresh-webui-api/issues/1194

Non-Mandatory BigDecimal fields inititalized with 0

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Mass_Disposal.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToGarbage.java

https://github.com/metasfresh/metasfresh/issues/5198

Gh5198 Mass disposal working increment

---

src/main/java/de/metas/ui/web/pickingslotsClearing/PackingHUsViewFactory.java
src/main/java/de/metas/ui/web/product/process/WEBUI_M_Product_LotNumber_Quarantine.java
src/main/java/de/metas/ui/web/window/descriptor/factory/NewRecordDescriptorsProvider.java

follow refactoring in metasfresh
https://github.com/metasfresh/metasfresh/issues/5204

5204-app - On-the-fly auto-allocate available HUs while creating shipments

---

src/main/java/de/metas/ui/web/pattribute/ASIDescriptorFactory.java

https://github.com/metasfresh/metasfresh/issues/5208

Gh5208 -- Attribute Age automatism

---

src/main/java/de/metas/location/geocoding/process/C_BPartner_SearchWithPrefilledDataProcess.java
src/main/java/de/metas/location/geocoding/process/C_BPartner_Window_AreaSearchProcess.java
src/main/java/de/metas/ui/web/document/filter/provider/locationAreaSearch/LocationAreaSearchDescriptor.java
src/main/java/de/metas/ui/web/document/filter/provider/locationAreaSearch/LocationAreaSearchDocumentFilterConverter.java
src/main/java/de/metas/ui/web/document/filter/provider/locationAreaSearch/LocationAreaSearchDocumentFilterDescriptorsProviderFactory.java
src/main/java/de/metas/ui/web/document/filter/sql/SqlDocumentFilterConverter.java
src/main/java/de/metas/ui/web/process/ProcessInstanceResult.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessPostProcessService.java
src/main/java/de/metas/ui/web/process/json/JSONProcessInstanceResult.java

https://github.com/metasfresh/metasfresh/issues/5238

Finetuning Area Search: Params from selected BPartner>>Location

---

src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java

in case of no mandatory logic, consider the field mandatory only if is displayed
https://github.com/metasfresh/metasfresh/issues/5266

GridTabVOBasedDocumentEntityDescriptorFactory.extractMandatoryLogic

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Mass_Disposal.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToGarbage.java

https://github.com/metasfresh/metasfresh/issues/5198

Gh5198 2 repairments

---

src/main/java/de/metas/ui/web/attachments/DocumentAttachmentsRestController.java
src/main/java/de/metas/ui/web/attachments/json/JSONAttachment.java
src/test/java/de/metas/ui/web/attachments/json/JSONAttachmentTest.java

https://github.com/metasfresh/metasfresh/issues/5261

JSONAttachment.allowDelete

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRowId.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewKeyColumnNamesMap.java
src/test/java/de/metas/ui/web/handlingunits/HUEditorRowIdTest.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1206

Gh1206webui

---

src/main/java/de/metas/ui/web/attachments/DocumentAttachments.java
src/main/java/de/metas/ui/web/attachments/DocumentAttachmentsRestController.java

https://github.com/metasfresh/metasfresh/issues/5261

5261 Prevent Users from Accidentally deleting attachment files

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Mass_Disposal.java
src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToGarbage.java

https://github.com/metasfresh/metasfresh/issues/5198

#5198-app refactoring

---

src/main/java/de/metas/location/geocoding/process/C_BPartner_Window_AreaSearchProcess.java
src/main/java/de/metas/ui/web/document/filter/provider/locationAreaSearch/LocationAreaSearchDocumentFilterConverter.java
src/main/java/de/metas/ui/web/document/filter/provider/locationAreaSearch/LocationAreaSearchDocumentFilterDescriptorsProvider.java

https://github.com/metasfresh/metasfresh/issues/5259

Area Search: New Param "Visit Address"

---

src/main/java/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntrySubTabBindingRepository.java
src/main/java/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoader.java
src/test/resources/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoaderTest.snap

change the widget type for datea-entry-date-fields to "date"
https://github.com/metasfresh/metasfresh/issues/5302

5302-app - Data Entry Date instead of Date-Time

---

src/main/java/de/metas/location/geocoding/process/C_BPartner_Window_AreaSearchProcess.java
src/main/java/de/metas/ui/web/config/SwaggerConfig.java
src/main/java/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryWebuiTools.java
src/main/java/de/metas/ui/web/view/ViewExcelExporter.java
src/main/java/de/metas/ui/web/view/ViewId.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentReferencesGroupList.java
src/main/java/de/metas/ui/web/window/model/DocumentChangeLogService.java
src/test/java/de/metas/ui/web/view/ViewIdTests.java

https://github.com/metasfresh/metasfresh/issues/5273

5273-app - BPartner REST-API

---

src/main/java/de/metas/ui/web/handlingunits/report/HUReportProcessInstancesRepository.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessDescriptorsFactory.java
src/main/java/de/metas/ui/web/process/descriptor/InternalName.java
src/main/java/de/metas/ui/web/process/descriptor/ProcessDescriptor.java
src/main/java/de/metas/ui/web/process/descriptor/WebuiRelatedProcessDescriptor.java
src/main/java/de/metas/ui/web/process/json/JSONDocumentAction.java
src/main/java/de/metas/ui/web/process/view/ViewActionDescriptor.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1219

gh1219webui

---

src/main/java/de/metas/ui/web/material/cockpit/rowfactory/CountingSubRowBucket.java
src/main/java/de/metas/ui/web/material/cockpit/rowfactory/DimensionGroupSubRowBucket.java
src/main/java/de/metas/ui/web/material/cockpit/rowfactory/MainRowBucket.java
src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputProcessor.java
src/main/java/de/metas/vertical/cables/webui/quickinput/CableSalesOrderLineQuickInputDescriptorFactory.java
src/test/java/de/metas/ui/web/material/cockpit/rowfactory/MaterialCockpitRowFactoryTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowFactoryTest.java
src/test/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsLoaderTest.java

https://github.com/metasfresh/metasfresh/issues/5348

#5348-app refactoring

---

src/main/java/de/metas/ui/web/pricing/process/M_DiscountSchemaBreak_CopyToOtherSchema.java

https://github.com/metasfresh/metasfresh/issues/5392

#5392 discount breaks copy process ( moved)

---

src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueCUQty.java

https://github.com/metasfresh/metasfresh/issues/5193

#5193 make the qtyCU parameter not mandatory

---

src/main/java/de/metas/ui/web/document/filter/DocumentFilterDescriptor.java
src/main/java/de/metas/ui/web/document/filter/DocumentFilterParamDescriptor.java
src/main/java/de/metas/ui/web/document/filter/json/JSONDocumentFilterDescriptor.java
src/main/java/de/metas/ui/web/document/filter/json/JSONDocumentFilterParamDescriptor.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
src/main/java/de/metas/ui/web/picking/husToPick/HUsToPickViewFilters.java
src/main/java/de/metas/ui/web/picking/pickingslot/PickingSlotViewFilters.java
src/main/java/de/metas/ui/web/process/ProcessRestController.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessDescriptorsFactory.java
src/main/java/de/metas/ui/web/process/adprocess/WebuiProcessClassInfo.java
src/main/java/de/metas/ui/web/process/descriptor/ProcessLayout.java
src/main/java/de/metas/ui/web/process/json/JSONProcessLayout.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayoutElement.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementDescriptor.java

https://github.com/metasfresh/metasfresh/issues/5139

gh5139_3 - implement BarcodeScannerType support (webui backend)

---

src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java

https://github.com/metasfresh/metasfresh/issues/5410

Gh5410 AllowCampaignPrice in Business Partner

---

src/main/java/de/metas/ui/web/dataentry/interceptor/DataEntryInterceptorUtil.java
src/main/java/de/metas/ui/web/debug/DebugRestController.java
src/main/java/de/metas/ui/web/debug/JSONCacheResetResult.java
src/main/java/de/metas/ui/web/window/model/DocumentCollection.java

also improve logging
https://github.com/metasfresh/metasfresh-webui-api/issues/1245

webui cache reset: don't invalidate new/changed documents

---

src/main/java/de/metas/ui/web/debug/DebugRestController.java
src/main/java/de/metas/ui/web/window/datatypes/json/DateTimeConverters.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDateConfig.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONLayoutWidgetType.java
src/test/java/de/metas/ui/web/window/datatypes/json/DateTimeConvertersTest.java

WARNING: to be integrated only when the frontend task is done
https://github.com/metasfresh/metasfresh/issues/5380
https://github.com/metasfresh/metasfresh-webui-frontend/issues/2317

drop support for legacy date/time formats and widgets

---

src/main/java/de/metas/ui/web/pricing/process/M_DiscountSchemaBreak_CopyToOtherSchema.java
src/main/java/de/metas/ui/web/pricing/process/M_DiscountSchemaBreak_CopyToOtherSchema_Product.java

https://github.com/metasfresh/metasfresh/issues/5470

Gh5470 Copy schema breaks with product parameter

---

src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLinesFromProductProposalsProducer.java
src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/5365

gh5365 - webui - JsonOLCandCreateRequest.dateOrdered

---

src/main/java/de/metas/ui/web/letter/LetterRestController.java
src/main/java/de/metas/ui/web/picking/husToPick/process/WEBUI_HUsToPick_PickCU.java
src/main/java/de/metas/ui/web/window/controller/Execution.java

https://github.com/metasfresh/metasfresh/issues/5365

ITrxManager: rename some methods to have a better naming

---

src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLinesFromProductProposalsProducer.java

https://github.com/metasfresh/metasfresh/issues/5515

Product Proposals: use product price's HU PI Item product if any

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_MoveToAnotherWarehouse_Helper.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1259

Filter available warehouses by what user types instead of always showing all of them

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorRowType.java

#1262  Implement receipt CU Label
https://github.com/metasfresh/metasfresh/issues/5540

#1262 Support HUStorage

---

src/main/java/de/metas/ui/web/attachments/DocumentAttachmentsRestController.java
src/main/java/de/metas/ui/web/view/SqlViewFactory.java
src/main/java/de/metas/ui/web/window/datatypes/DocumentId.java
src/main/java/de/metas/ui/web/window/datatypes/DocumentPath.java
src/main/java/de/metas/ui/web/window/model/DocumentReferencesService.java

https://github.com/metasfresh/metasfresh/issues/5562

gh2853: don't fetch references and attachments for composed keys

---

src/main/java/de/metas/ui/web/dashboard/KPIDataLoader.java

https://github.com/metasfresh/metasfresh/issues/5449

gh5449 - minor refactoring

---

src/main/java/de/metas/ui/web/document/filter/provider/locationAreaSearch/LocationAreaSearchDocumentFilterConverter.java
src/main/java/de/metas/ui/web/document/filter/provider/locationAreaSearch/LocationAreaSearchDocumentFilterDescriptorsProviderFactory.java

https://github.com/metasfresh/metasfresh/issues/5566

 Add integration with Google Maps

---

src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitRow.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java
src/test/java/de/metas/ui/web/material/cockpit/rowfactory/MaterialCockpitRowFactoryTest.java

* refactoring: when i recreate the model classes, some getter were gone, so i refactored where necessary
https://github.com/metasfresh/metasfresh/issues/5575

5575-app - Add `ExternalId` to Product

---

src/main/java/de/metas/ui/web/pickingV2/config/PickingConfigV2.java
src/main/java/de/metas/ui/web/pickingV2/packageable/process/PackageablesViewBasedProcess.java
src/main/java/de/metas/ui/web/pickingV2/packageable/process/PackageablesView_OpenProductsToPick.java
src/main/java/de/metas/ui/web/pickingV2/packageable/process/PackageablesView_PrintPicklist.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRowsRepository.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_PickSelected.java

https://github.com/metasfresh/metasfresh/issues/5659
#5659 Picklist in Picking Terminal v2 automatically picks, but shall not

#5659 Picklist in Picking Terminal v2 automatically picks, but shall not 

---

src/main/java/de/metas/ui/web/picking/husToPick/HUsToPickViewFilters.java
src/main/java/de/metas/ui/web/pickingV2/config/PickingConfigRepositoryV2.java
src/main/java/de/metas/ui/web/pickingV2/config/PickingConfigV2.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRowsDataFactory.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRowsRepository.java

https://github.com/metasfresh/metasfresh/issues/5551

gh5551_2: (webui) picking v2 shall consider shipment attributes (configurable)

---

src/main/java/de/metas/ui/web/order/pricingconditions/process/PricingConditionsView_CopyRowToEditable.java

minor - follow refactoring in metasfresh
https://github.com/metasfresh/metasfresh/issues/5656

5656-app - EDI-Tweaks

---

src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_M_Source_HU_IssueCUQty.java
src/main/java/de/metas/ui/web/quickinput/IQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/QuickInput.java
src/main/java/de/metas/ui/web/quickinput/WindowQuickInputRestController.java
src/main/java/de/metas/ui/web/quickinput/forecastline/ForecastLineQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/inout/EmptiesQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/invoiceline/InvoiceLineQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
src/main/java/de/metas/vertical/cables/webui/quickinput/CableSalesOrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/5679

gh5679: BOMUse=Phantom (webui)

---

src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/view/descriptor/ViewLayout.java
src/main/java/de/metas/ui/web/view/json/JSONViewLayout.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1287

Customer Proposal List: tell frontend that Qty is the first field to focus

---

src/main/java/de/metas/ui/web/material/cockpit/MaterialCockpitRowRepository.java
src/main/java/de/metas/ui/web/material/cockpit/filters/ProductFilterUtil.java

https://github.com/metasfresh/metasfresh/issues/5740

#5740 Fix compiling issues

---

src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableRowsRepository.java
src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableViewFilterVO.java
src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableViewFilters.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_4EyesReview_ProcessAll.java

https://github.com/metasfresh/metasfresh/issues/5743

Gh5743 Shipper in ProductsToPick_4EyesReview_ProcessAll

---

src/main/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRow.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRowsDataFactory.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_4EyesReview_ProcessAll.java

https://github.com/metasfresh/metasfresh/issues/5743

Gh5743 improvements for Shipper parameter in the process

---

src/main/java/de/metas/ui/web/order/products_proposal/campaign_price/StandardCampaignPriceProvider.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java

https://github.com/metasfresh/metasfresh/issues/5756

#5756 Use pricing sytem when creating proposals

---

src/main/java/de/metas/ui/web/pickingV2/productsToPick/process/ProductsToPick_4EyesReview_ProcessAll.java

https://github.com/metasfresh/metasfresh/issues/5743

#5743 parameter callout for ShipperId change

---

src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableRow.java
src/main/java/de/metas/ui/web/pickingV2/packageable/PackageableRowsRepository.java

https://github.com/metasfresh/metasfresh/issues/5767

#5767 sort the lines in picking terminal 2

---

src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRow.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsLoader.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsRepository.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1303

gh1303webui

---

src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRow.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsLoader.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1305

shipment schedule editor: pimp layout + show packing instructions

---

src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/picking/pickingslot/process/WEBUI_Picking_PickQtyToNewHU.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1307

gh1307webui

---

src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsData.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/service/Order.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLine.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLinesFromProductProposalsProducer.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
src/main/java/de/metas/ui/web/order/products_proposal/view/BasePLVProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalView.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalViewFactoryTemplate.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1309

gh1309webui

---

src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowActions.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowChangeRequest.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowReducers.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLine.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderLinesFromProductProposalsProducer.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1311

product proposal: add Description field and make it editable

---

src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsRowsLoader.java
src/main/java/de/metas/ui/web/pricing/process/M_DiscountSchemaBreak_CopyToOtherSchema.java
src/main/java/de/metas/ui/web/pricing/process/M_DiscountSchemaBreak_CopyToOtherSchema_Product.java

https://github.com/metasfresh/metasfresh/issues/5799

feat: Pricelist Schema export-import

---

src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsData.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/service/Order.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
src/main/java/de/metas/ui/web/order/products_proposal/view/OrderProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/order/products_proposal/view/ProductsProposalView.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1315

product proposal view: show customer name in header

---

src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRow.java
src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1317

product proposals: order products by M_ProductPrice.SeqNo and then by product name

---

src/main/java/de/metas/ui/web/order/pricingconditions/view/PricingConditionsView.java

Gh5806 app

---

src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
src/main/java/de/metas/ui/web/order/products_proposal/view/BPartnerProductsProposalViewFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/ProductLookupDescriptor.java
src/test/resources/de/metas/dataentry/layout/DataEntryLayoutRepositoryTest.snap

https://github.com/metasfresh/metasfresh/issues/5802

Gh5802 Pricelist mutation and product proposal changes

---

src/main/java/de/metas/ui/web/payment_allocation/ImmutableRowsIndex.java
src/main/java/de/metas/ui/web/payment_allocation/InvoiceRow.java
src/main/java/de/metas/ui/web/payment_allocation/InvoiceRows.java
src/main/java/de/metas/ui/web/payment_allocation/InvoicesView.java
src/main/java/de/metas/ui/web/payment_allocation/InvoicesViewFactory.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRows.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentRow.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentRows.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentViewFactory.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentsView.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentsViewFactory.java
src/main/java/de/metas/ui/web/payment_allocation/process/InvoicesViewBasedProcess.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentView_Launcher.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsViewBasedProcess.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_Allocate.java
src/main/java/de/metas/ui/web/process/adprocess/ViewBasedProcessTemplate.java
src/main/java/de/metas/ui/web/view/IViewsRepository.java
src/main/java/de/metas/ui/web/view/ViewId.java
src/main/java/de/metas/ui/web/view/ViewsRepository.java
src/main/java/de/metas/ui/web/view/template/AbstractCustomView.java
src/main/java/de/metas/ui/web/view/template/IRowsData.java
src/test/java/de/metas/ui/web/view/ViewIdTests.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1320

gh1320webui

---

src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputProcessor.java

https://github.com/metasfresh/metasfresh/issues/5880

OrderLineQuickInputProcessor: use BOM line's attributes if any

---

src/main/java/de/metas/ui/web/payment_allocation/ImmutableRowsIndex.java
src/main/java/de/metas/ui/web/payment_allocation/InvoiceRow.java
src/main/java/de/metas/ui/web/payment_allocation/InvoiceRows.java
src/main/java/de/metas/ui/web/payment_allocation/InvoicesView.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentRow.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentRows.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentsView.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentsViewFactory.java
src/main/java/de/metas/ui/web/payment_allocation/process/InvoicesView_AddAdditionalInvoice.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentView_Launcher.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentView_Launcher_FromPayment.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentView_Launcher_From_BPartnerSingleDocument.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentView_Launcher_From_BPartnerView.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_AddAdditionalPayment.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_Allocate.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_AllocateAndDiscount.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_AllocateAndWriteOff.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_Allocate_Template.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessDescriptorsFactory.java
src/main/java/de/metas/ui/web/process/descriptor/WebuiRelatedProcessDescriptor.java
src/main/java/de/metas/ui/web/process/json/JSONDocumentAction.java
src/main/java/de/metas/ui/web/window/datatypes/DocumentIdsSelection.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1320

gh1320webui_2

---

src/main/java/de/metas/ui/web/pickingV2/productsToPick/rows/ProductsToPickRowsService.java

#5865 Picklist not working: "Type not supported: UNALLOCABLE"
https://github.com/metasfresh/metasfresh/issues/5865

#5865 Add meaningful message 

---

src/main/java/de/metas/ui/web/quickinput/inout/EmptiesQuickInputProcessor.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRow.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidatesView.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidatesViewFactory.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/process/ShipmentCandidatesView_Launcher.java
src/main/java/de/metas/ui/web/view/IEditableView.java
src/main/java/de/metas/ui/web/view/ViewRowEditRestController.java

EDI support multiple SSCCs per DESADV-Line metasfresh/metasfresh#5847

5846-app - EDI support multiple SSCCs per DESADV-Line

---

src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputCallout.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputDescriptorFactory.java

https://github.com/metasfresh/metasfresh/issues/5940

OrderLineQuickInputCallout: change how we preselect the HU PI Item Product

---

src/main/java/de/metas/ui/web/shipment_candidates_editor/PackingInfo.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRow.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowUserChangeRequest.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRows.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsLoader.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidateRowsRepository.java
src/main/java/de/metas/ui/web/shipment_candidates_editor/ShipmentCandidatesView.java

https://github.com/metasfresh/metasfresh/issues/5946

shipment dispo quick edit: handle qty entered as TU or CU

---

src/main/java/de/metas/ui/web/inout/process/InOutToTransportationOrderService.java

https://github.com/metasfresh/metasfresh/issues/5885

Add handling to process for adding InOut to ShipperTransportation when InOut has no HUs

---

src/main/java/de/metas/ui/web/inout/process/InOutToTransportationOrderService.java

https://github.com/metasfresh/metasfresh/issues/5885

Tour dependent adjustments: finetuning

---

src/main/java/de/metas/ui/web/process/adprocess/ADProcessInstancesRepository.java
src/test/java/de/metas/ui/web/process/adprocess/ProcessInfoInternalParametersTest.java

#1343 Add an unit test for how the selected rows ids are sent as parameters

#1343 Add an unit test for how the selected rows ids are sent as parameters 

---

src/main/java/de/metas/ui/web/document/filter/sql/SqlParamsCollector.java
src/main/java/de/metas/ui/web/window/controller/WindowRestController.java
src/main/java/de/metas/ui/web/window/datatypes/DocumentPath.java
src/main/java/de/metas/ui/web/window/model/Document.java
src/main/java/de/metas/ui/web/window/model/DocumentQuery.java
src/main/java/de/metas/ui/web/window/model/HighVolumeReadWriteIncludedDocumentsCollection.java
src/main/java/de/metas/ui/web/window/model/HighVolumeReadonlyIncludedDocumentsCollection.java
src/main/java/de/metas/ui/web/window/model/IIncludedDocumentsCollection.java
src/main/java/de/metas/ui/web/window/model/OrderedDocumentsList.java
src/main/java/de/metas/ui/web/window/model/SingleRowDetailIncludedDocumentsCollection.java
src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentQueryBuilder.java

https://github.com/metasfresh/metasfresh-webui-api/issues/1340

Implement GET /rest/api/window/{windowId}/{documentId}/{tabId}?ids=comma separated rowIds 

---

src/main/java/de/metas/ui/web/process/adprocess/ADProcessInstanceController.java

refs: https://github.com/metasfresh/metasfresh/issues/3852

Export of Jasper Reports to Excel

---

src/main/java/de/metas/ui/web/document/filter/provider/standard/StandardDocumentFilterDescriptorsProviderFactory.java

https://github.com/metasfresh/metasfresh/issues/6065

Gh6065 1 workaround for date+time range filters

---

src/main/java/de/metas/ui/web/pickingV2/productsToPick/rows/factory/AllocablePackageable.java
src/main/java/de/metas/ui/web/pickingV2/productsToPick/rows/factory/ProductsToPickRowsDataFactory.java
src/test/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRowsDataFactoryTest.java

https://github.com/metasfresh/metasfresh/issues/6116

Picklist report process breaks picking

---

src/main/java/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoader.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayoutElementField.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementFieldDescriptor.java
src/test/resources/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoaderTest.snap

https://github.com/metasfresh/metasfresh/issues/6119

JSONDocumentLayoutElementField.clearValueText

---

src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentQueryBuilder.java

https://github.com/metasfresh/metasfresh/issues/6129

refs: https://github.com/metasfresh/metasfresh/issues/6129

---

src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputCallout.java

* code fix after change in metasfresh
metasfresh/metasfresh#6142

6142-app - don't fail shipmentsched creation if order line has no PiiP

---

src/main/java/de/metas/ui/web/pickingV2/productsToPick/rows/factory/ProductsToPickRowsDataFactory.java
src/test/java/de/metas/ui/web/pickingV2/productsToPick/PickingV2TestHelper.java
src/test/java/de/metas/ui/web/pickingV2/productsToPick/ProductsToPickRowsDataFactoryTest.java

https://github.com/metasfresh/metasfresh/issues/6116

always use QtyToDeliver when calculating the qtyToAllocateTarget

---

src/main/java/de/metas/ui/web/quickinput/field/DefaultPackingItemCriteria.java
src/main/java/de/metas/ui/web/quickinput/field/PackingItemProductFieldHelper.java
src/main/java/de/metas/ui/web/quickinput/invoiceline/IInvoiceLineQuickInput.java
src/main/java/de/metas/ui/web/quickinput/invoiceline/InvoiceLineQuickInputCallout.java
src/main/java/de/metas/ui/web/quickinput/invoiceline/InvoiceLineQuickInputDescriptorFactory.java
src/main/java/de/metas/ui/web/quickinput/invoiceline/InvoiceLineQuickInputProcessor.java
src/main/java/de/metas/ui/web/quickinput/orderline/OrderLineQuickInputCallout.java

https://github.com/metasfresh/metasfresh/issues/6201

Support packing instructions for invoice line 'Batch entry'

---

src/main/java/de/metas/ui/web/window/datatypes/json/JSONLookupValueValidationInformation.java

https://github.com/metasfresh/metasfresh/issues/6154

#6154 Added title field to validation information object

---

src/main/java/de/metas/ui/web/document/filter/json/JSONDocumentFilterDescriptor.java
src/test/java/de/metas/ui/web/document/filter/json/JSONDocumentFilterDescriptorTest.java

https://github.com/metasfresh/metasfresh-webui-frontend/issues/2556

provide filters already grouped

---

src/main/java/de/metas/ui/web/window/datatypes/json/JSONLookupValue.java

https://github.com/metasfresh/metasfresh/issues/6154

#6154 Fix for error while voiding documents.

---

src/main/java/de/metas/ui/web/attachments/DocumentAttachments.java
src/main/java/de/metas/ui/web/attachments/DocumentAttachmentsRestController.java

https://github.com/metasfresh/metasfresh/issues/6328

ESR Import + processing autom. after upload via drag&drop

---

src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java

https://github.com/metasfresh/metasfresh/issues/6346

#6346 Added Create Request Process to Shipment Window and Customized it to create complaint from a shipment document.

---

src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_HU_Transform.java
src/main/java/de/metas/ui/web/handlingunits/process/WebuiHUTransformParametersFiller.java
src/main/java/de/metas/ui/web/handlingunits/util/WEBUI_ProcessHelper.java

https://github.com/metasfresh/metasfresh/issues/6350

Set default values for `HU Editor-> Transform Action -> CU to New TUs`

---

src/main/java/de/metas/ui/web/request/process/WEBUI_CreateRequest.java

https://github.com/metasfresh/metasfresh/issues/6346

#6346 Showing movement date field for shipment complaints and prefilling it.

---

src/main/java/de/metas/ui/web/window/model/sql/SqlDocumentsRepository.java

* follow refactoring in metasfresh
metasfresh/metasfresh#6320

support manual invoice as commission trigger

---

src/main/java/de/metas/ui/web/document/filter/DocumentFilterList.java
src/main/java/de/metas/ui/web/handlingunits/DefaultHUEditorViewFactory.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewBuilder.java
src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
src/main/java/de/metas/ui/web/handlingunits/process/HUMoveToDirectWarehouseService.java
src/main/java/de/metas/ui/web/view/SqlViewFactory.java
src/main/java/de/metas/ui/web/view/descriptor/SqlViewSelectionQueryBuilder.java
src/main/java/de/metas/ui/web/view/descriptor/ViewLayoutFactory.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/sql/SqlOrderByValue.java

https://github.com/metasfresh/metasfresh/issues/6365

Check/ Fix Barcode Filtering and `Materialentnahme`=`Material Withdrawal` refresh

---

src/main/java/de/metas/ui/web/window/datatypes/json/DateTimeConverters.java
src/test/java/de/metas/ui/web/window/datatypes/json/DateTimeConvertersTest.java

https://github.com/metasfresh/metasfresh/issues/6390

Fix User Queries with date throwing error

---

src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayoutElement.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentFieldWidgetType.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutElementDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/GridTabVOBasedDocumentEntityDescriptorFactory.java
src/main/java/de/metas/ui/web/window/descriptor/factory/standard/LayoutFactory.java
src/test/resources/de/metas/ui/web/dataentry/window/descriptor/factory/DataEntryTabLoaderTest.snap

https://github.com/metasfresh/metasfresh-webui-api/issues/1394

JSONDocumenLayoutElement.maxLength

---

src/main/java/de/metas/ui/web/window/datatypes/json/DateTimeConverters.java

https://github.com/metasfresh/metasfresh/issues/6390

Use explicit data type instead of Object

---

src/main/java/de/metas/ui/web/dashboard/json/JsonUserDashboardItemAddRequest.java
src/test/java/de/metas/ui/web/dashboard/json/JsonUserDashboardItemAddRequestTest.java

https://github.com/metasfresh/metasfresh/issues/6413

Fix serialization issue

---

src/main/java/de/metas/ui/web/document/filter/DocumentFilterDescriptor.java
src/main/java/de/metas/ui/web/document/filter/json/JSONDocumentFilterDescriptor.java
src/main/java/de/metas/ui/web/document/filter/provider/CompositeDocumentFilterDescriptorsProvider.java
src/main/java/de/metas/ui/web/document/filter/provider/DocumentFilterDescriptorsConstants.java
src/main/java/de/metas/ui/web/document/filter/provider/fullTextSearch/FullTextSearchDocumentFilterDescriptorsProviderFactory.java
src/main/java/de/metas/ui/web/document/filter/provider/standard/StandardDocumentFilterDescriptorsProviderFactory.java
src/main/java/de/metas/ui/web/document/filter/provider/userQuery/UserQueryDocumentFilterDescriptorsProvider.java
src/main/java/de/metas/ui/web/document/filter/provider/userQuery/UserQueryDocumentFilterDescriptorsProviderFactory.java
src/main/java/de/metas/ui/web/document/geo_location/GeoLocationDocumentService.java
src/main/java/de/metas/ui/web/window/datatypes/DebugProperties.java
src/main/java/de/metas/ui/web/window/datatypes/LookupValuesList.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayout.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONLookupValuesList.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutDescriptor.java
src/main/java/de/metas/ui/web/window/model/DocumentFieldChange.java
src/main/java/de/metas/ui/web/window/model/lookup/GenericSqlLookupDataSourceFetcher.java
src/test/java/de/metas/ui/web/document/filter/json/JSONDocumentFilterDescriptorTest.java
src/test/java/de/metas/ui/web/window/datatypes/LookupValuesListTest.java
src/test/java/de/metas/ui/web/window/datatypes/json/JSONLookupValuesListTest.java

https://github.com/metasfresh/metasfresh/issues/6390

make sure filters are sorted correctly

---

src/main/java/de/metas/ui/web/handlingunits/HUEditorRow.java
src/main/java/de/metas/ui/web/handlingunits/SqlHUEditorViewRepository.java

https://github.com/metasfresh/metasfresh/issues/6446

#6446 Showing if rows have an own palette set in the handling unit editor window.

---

src/main/java/de/metas/ui/web/accounting/process/Fact_Acct_OpenLinkedFacts_GridView.java
src/main/java/de/metas/ui/web/accounting/process/Fact_Acct_OpenLinkedFacts_ProcessHelper.java
src/main/java/de/metas/ui/web/accounting/process/Fact_Acct_OpenLinkedFacts_SingleView.java
src/main/java/de/metas/ui/web/process/adprocess/ADProcessPostProcessService.java

https://github.com/metasfresh/metasfresh/issues/6432

Gh6432 open linked accounts processes

---

src/main/java/de/metas/ui/web/document/filter/provider/userQuery/UserQueryDocumentFilterDescriptorsProviderFactory.java
src/main/java/de/metas/ui/web/window/model/sql/SqlValueConverters.java
src/test/java/de/metas/ui/web/window/model/sql/SqlValueConvertersTest.java

https://github.com/metasfresh/metasfresh/issues/6476

User Query filters errors

---

src/main/java/de/metas/ui/web/window/descriptor/factory/DocumentDescriptorFactory.java
src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
src/main/java/de/metas/ui/web/window/model/DocumentsRepository.java

https://github.com/metasfresh/metasfresh/issues/6482

Cloning with keyboard shortcut works even if action is hidden from menu

---

src/main/java/de/metas/ui/web/payment_allocation/InvoiceRow.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentAndInvoiceRowsRepo.java
src/main/java/de/metas/ui/web/payment_allocation/PaymentRow.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommand.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_Allocate.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_AllocateAndDiscount.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_AllocateAndWriteOff.java
src/main/java/de/metas/ui/web/payment_allocation/process/PaymentsView_Allocate_Template.java
src/test/java/de/metas/ui/web/payment_allocation/process/PaymentsViewAllocateCommandTest.java

https://github.com/metasfresh/metasfresh/issues/6529

Allow Invoice with Credit memo allocation

---

src/main/java/de/metas/ui/web/window/datatypes/DebugProperties.java
src/main/java/de/metas/ui/web/window/datatypes/LookupValuesList.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONDocumentLayout.java
src/main/java/de/metas/ui/web/window/datatypes/json/JSONLookupValuesList.java
src/main/java/de/metas/ui/web/window/descriptor/DocumentLayoutDescriptor.java
src/main/java/de/metas/ui/web/window/descriptor/factory/DocumentDescriptorFactory.java
src/main/java/de/metas/ui/web/window/model/DocumentCollection.java
src/main/java/de/metas/ui/web/window/model/DocumentFieldChange.java
src/main/java/de/metas/ui/web/window/model/DocumentsRepository.java
src/main/java/de/metas/ui/web/window/model/lookup/GenericSqlLookupDataSourceFetcher.java
src/main/java/de/metas/ui/web/window/model/sql/SqlValueConverters.java
src/test/java/de/metas/ui/web/window/datatypes/LookupValuesListTest.java
src/test/java/de/metas/ui/web/window/datatypes/json/JSONLookupValuesListTest.java
src/test/java/de/metas/ui/web/window/model/sql/SqlValueConvertersTest.java

...latest window REST API changes
https://github.com/metasfresh/metasfresh/issues/6245

attempt to solve problem on yeast_overgrowth by synching..
